### ISSUE TITLE
downloads.buddycloud.com down?

### ISSUE THREAD

**Issue by mhingston** [buddycloud/dockerfiles#5]
When running the docker file...

```
Step 20 : ADD http://downloads.buddycloud.com/packages/debian/nightly/buddycloud-server-java/buddycloud-server-java_latest.deb  /tmp/buddycloud-server.deb
2014/12/20 13:07:20 Got HTTP status code >= 400: 404 Not Found
```

[http://downloads.buddycloud.com](http://downloads.buddycloud.com) just has an apache test page at the time of posting.

**Comment by imaginator** [comment]
@abmargb did you change something recently in the apache config?

**Comment by abmargb** [comment]
No. I didn't. I'll take a look at this.

On Sun, Dec 21, 2014 at 11:42 AM, Simon Tennant notifications@github.com
wrote:

> @abmargb https://github.com/abmargb did you change something recently
> in the apache config?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/buddycloud/dockerfiles/issues/5#issuecomment-67772402
> .

## 

Abmar Barros
MSc in Computer Science from the Federal University of Campina Grande -
www.ufcg.edu.br
Fogbow Team Leader - http://fogbowcloud.org
Buddycloud Dev - www.buddycloud.org
Paraíba - Brazil

**Comment by abmargb** [comment]
We're back now.

I fixed a couple of issues related to
http://httpd.apache.org/docs/2.4/upgrading.html, e.g. appending .conf to
virtual hosts files and adding an Access Control rule for /var/web.

On Sun, Dec 21, 2014 at 11:43 AM, Abmar Barros abmargb@gmail.com wrote:

> No. I didn't. I'll take a look at this.
> 
> On Sun, Dec 21, 2014 at 11:42 AM, Simon Tennant notifications@github.com
> wrote:
> 
> > @abmargb https://github.com/abmargb did you change something recently
> > in the apache config?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/buddycloud/dockerfiles/issues/5#issuecomment-67772402
> > .
> 
> ## 
> 
> Abmar Barros
> MSc in Computer Science from the Federal University of Campina Grande -
> www.ufcg.edu.br
> Fogbow Team Leader - http://fogbowcloud.org
> Buddycloud Dev - www.buddycloud.org
> Paraíba - Brazil

## 

Abmar Barros
MSc in Computer Science from the Federal University of Campina Grande -
www.ufcg.edu.br
Fogbow Team Leader - http://fogbowcloud.org
Buddycloud Dev - www.buddycloud.org
Paraíba - Brazil

**Comment by abmargb** [comment]
I suppose that's related to recent upgrades to trusty?

**Comment by imaginator** [comment]
Oh thanks dude - I should have run the upagrade on our test kit before... Man it was a long week!
